server:
    address: localhost
    port: 8080

spring:
    thymeleaf:
        prefix: classpath:templates/
        suffix: .html
        cache: false

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: ehdgus93!

mybatis:
    type-aliases-package: com.example.demo.dto
    mapper-locations: classpath:mappers/*.xml
    configuration:
        map-underscore-to-camel-case: true

logging:
    level:
        com.example.demo.mapper: debug